### ISSUE TITLE
Project Add Parts Issue Ver 0.82

### ISSUE THREAD

**Issue by easman95** [partkeepr/PartKeepr#618]
Hello, I hope I'm posting in the right place. I have an issue adding parts/searching for parts when creating a new project. Here is the error message from the Critical Error Report:

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://localhost:8080/partkeepr/web/api/parts?_dc=1458073445609

Response Status Code
==================================
500

Response
==================================
<br />
<b>Fatal error</b>:  Call to a member function getName() on null in <b>C:\Program Files (x86)\xampp\htdocs\partkeepr\src\PartKeepr\PartBundle\Entity\Part.php</b> on line <b>816</b><br />
{"@context":"\/partkeepr\/web\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Error: Call to a member function getName() on null"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.12
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

Here is some XHR stuff from when the logs are set to debugging (as per your wiki page):

{"@context":"\/partkeepr\/web\/api\/contexts\/SystemNotice","@id":"\/partkeepr\/web\/api\/system_notices?_dc=1458073337718\u0026page=1\u0026start=0\u0026itemsPerPage=99999999","@type":"hydra:PagedCollection","hydra:totalItems":2,"hydra:itemsPerPage":99999999,"hydra:firstPage":"\/partkeepr\/web\/api\/system_notices?_dc=1458073337718\u0026start=0\u0026itemsPerPage=99999999","hydra:lastPage":"\/partkeepr\/web\/api\/system_notices?_dc=1458073337718\u0026start=0\u0026itemsPerPage=99999999","hydra:member":[{"@id":"\/partkeepr\/web\/api\/system_notices\/1","@type":"SystemNotice","date":"2016-03-11T11:47:10-05:00","title":"New PartKeepr Version 0.81 available","description":"PartKeepr Version 0.81\n\nList of bugfixes: https:\/\/github.com\/partkeepr\/PartKeepr\/issues?q=is%3Aissue+milestone%3A0.80+is%3Aclosed changelog:","acknowledged":false,"type":"PARTKEEPR_VERSION_0.81"},{"@id":"\/partkeepr\/web\/api\/system_notices\/2","@type":"SystemNotice","date":"2016-03-14T13:04:29-04:00","title":"New PartKeepr Version 0.82 available","description":"PartKeepr Version 0.82\n\nThis release fixes the 0.81 issue where part attachments aren\u0027t visible, see https:\/\/github.com\/partkeepr\/PartKeepr\/issues\/612 changelog:","acknowledged":false,"type":"PARTKEEPR_VERSION_0.82"}],"hydra:search":{"@type":"hydra:IriTemplate","hydra:template":"\/partkeepr\/web\/api\/system_notices{?}","hydra:variableRepresentation":"BasicRepresentation","hydra:mapping":[]}}

I don't see anything relevant in the apps/logs/dev.log file (Hopefully I did this right)

...Sorry I'm really new to all of this.

**Comment by felicitus** [comment]
Possible duplicate of #613. If not, please check if the issue can be reproduced on https://demo.partkeepr.org - if so, please provide detailed steps on how to reproduce the issue.

**Comment by easman95** [comment]
Thank you for your quick response on this. Here's what I have done so far:

**1.)** I have viewed issue #613  - The error message is similar (Critical Response Returned: Call to a member function getType() on null) however, this happens when I attempt to add a part to the newly created project (I will explain further below). The issue, at least for me, does not appear to be the same as issue #613.

**2.)** I have tried to reproduce the issue on https://demo.partkeepr.org, but I was not able to.

**3.)** Detailed steps on how to reproduce the problem on my end:

**a.)** Log into system, select "Edit" --> Projects
**b.)** Click the add projects button on the upper left-hand side
**c.) **Enter "Project Name" and "Project Description" (i.e. "Test 1", "Testing")
**d.) **Under "Project Parts" I click the "Add" button and at this point, a Quantity of "1" appears and the "Part" field is blank
**e.)** When I click the blank area under the "Part" column - a dialog box appears to search for existing parts (So that I can add the part to the project) and at this step is where the issue occurs:

"Critical Error The server returned a response which we were not able to interpret."

 The only option I have at this point is to click "OK".

Debug Mode: Displays the message above then displays this message (See below): 

"Critical Response Returned: Call to a member function getType() on null"

After clicking "OK" nothing is populated under the "Part" column.

Note: To be quite honest, I do not know for sure if this was happening previously with the last version I was on (ver 0.79) and this may or may not be a problem with the current version I am on (ver 0.82)

If I have missed anything or I did something wrong, please let me know.

Your help with this is greatly appreciated - Thank you for your time.

**Comment by felicitus** [comment]
Here are a few things you could try:

1. Re-run setup so that all caches are re-generated
2. If that doesn't help, try to use [app_dev.php (partkeepr wiki)](https://wiki.partkeepr.org/wiki/How_to_Debug#Backend_Debugging). If you use `app_dev.php` the error dialogs should have a backtrace like so:
![untitled](https://cloud.githubusercontent.com/assets/162974/13814924/b85d59a8-eb88-11e5-9373-918715887298.png)

I noticed an inconsistency in your description. The initial issue says that you encounter "Fatal error: Call to a member function getName() on null" but today you say it's "Critical Error The server returned a response which we were not able to interpret.". Can you clarify?

**Comment by felicitus** [comment]
Another possibility is that the issue was already fixed, I'll release 0.83 soon, so you can double-check then.

**Comment by easman95** [comment]
1.) I have tried to re-run setup, but it errors out during "Testing for correct PHP settings" with a "Invalid Reponse from server" and when i click the "Show Errors" a pop-up dialog box appears stating " Error Details: Invalid Response from server"

2.) I have tried to use the app_dev.php method, but it seems to hang, and I do not see a login prompt at all.

Note: I have restarted the server/services after the experiences listed above - but I still have the same  issues.

As for your statement regarding i**nconsistencies in the description**, I apologize for that and what I should've clarified is:

The error message I first received was during debug mode ("Fatal error: Call to a member function getName() on null")

The other error message I receive happens when I am not in debug mode ("Critical Error The server returned a response which we were not able to interpret.") - while I log in normally

A question I have for right now is: Should I "undo" the debug mode and re-run the partkeepr setup? Would debug mode have any effect on your instructions for 1.) Re-run setup... and 2.) If that doesn't help, try to use app_dev.php (partkeepr wiki).....?

Again, thank you for your quick responses to this.

**Comment by easman95** [comment]
Sorry just saw this: "Another possibility is that the issue was already fixed, I'll release 0.83 soon, so you can double-check then."

OK, thank you for the update.

**Comment by easman95** [comment]
I upgraded to 1.0.0-alpha.1 but the issue still persists. I have narrowed it down to a couple of bad folders, but partkeepr doesn't allow me to delete these "bad" folders. I get the following error message below, and the folder does not delete at all:

An error occurred

Details
==================================
An exception occurred while executing 'DELETE FROM PartCategory WHERE id = ?' with params [16]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`part`, CONSTRAINT `FK_E93DDFF812469DE2` FOREIGN KEY (`category_id`) REFERENCES `partcategory` (`id`))

Request
==================================
DELETE /partkeepr/web/api/part_categories/16?_dc=1458827441479

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/partkeepr\/web\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"An exception occurred while executing \u0027DELETE FROM PartCategory WHERE id = ?\u0027 with params [16]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`part`, CONSTRAINT `FK_E93DDFF812469DE2` FOREIGN KEY (`category_id`) REFERENCES `partcategory` (`id`))"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.12
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by felicitus** [comment]
I believe you are mixing up problems.

The initial report says: "I have an issue adding parts/searching for parts when creating a new project.". Now you state that you are trying to delete a category. Please open a ```separate``` issue per issue, otherwise it's impossible for me to fix things.

**Comment by easman95** [comment]
I cannot see any of the parts at all to "unassign it". I believe these folders are the source of this original issue.

Thank you I will create a separate issue.

**Comment by felicitus** [comment]
I see. Well what you could do is to send me a database dump (use timo at partkeepr dot com ) and I'll try to reproduce it on my system, but it'll take a few weeks as I'm in holiday from tomorrow.

**Comment by felicitus** [comment]
Can you send a database dump to me? Without it I won't be able to reproduce and fix the issue.

**Comment by felicitus** [comment]
Nevermind, I believe I have found to root cause, so no database dump is required.

**Comment by felicitus** [comment]
Please try the latest PartKeepr version, the issue should now be fixed. If not, please re-open.
